# Generated by Django 4.1.3 on 2022-11-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rmbg_img',
            field=models.ImageField(blank=True, upload_to='image_rmbg'),
        ),
    ]
